application/blueprints/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user
from application.blueprints.users.models import User
from application.extensions import db, bcrypt

login_bp = Blueprint("login", __name__, template_folder="templates")


@login_bp.route("/login", methods=["POST"])
def login():
    data = request.form.to_dict()
    try:
        user = User.query.filter_by(username=data.get("username")).one()
    except Exception as e:
        user = None
    if user and bcrypt.check_password_hash(user.password, data.get("password")):
        login_user(user, remember=True)
        flash("Logged in successfully.", "success")
    else:
        flash("Username or password incorrect.", "danger")
    return redirect(url_for("homepage.homepage"))


@login_bp.route("/register", methods=["POST"])
def register():
    data = request.form.to_dict()

    user = User()

    user.first_name = data.get("first_name")
    user.last_name = data.get("last_name")
    user.email = data.get("email")
    user.phone_number = data.get("phone_number")
    user.username = data.get("username")
    user.password = bcrypt.generate_password_hash(data.get("password")).decode("utf-8")

    db.session.add(user)
    db.session.commit()

    login_user(user, remember=True)

    flash("Registered successfully.", "success")
    return redirect(url_for("homepage.homepage"))

application/blueprints/templates/base.html
<!doctype html>
<html id="html" lang="en" class="">
    <head data-bs-theme="dark">

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/output.css') }}">
    
        <title>{% block title %} {% endblock %}</title>
    </head>
    <body>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="max-w-5xl mx-auto px-4">
                        <div class="flash-{{category}}">
                            {{message}}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
    </body>
</html>

application/blueprints/templates/dashboard.html
<PageLayout title="Dashboard">
    <Container>
        <Navbar active-link="dashboard"></Navbar>
        <h1>Dashboard</h1>
        <div class="grid grid-cols-2">
            <div class="col-span-2">
                <h4>Bulletin Board</h4>
                <p>Imagine a huge list of announcements here.</p>
            </div>
            <div>
                <h4>Recent Orders</h4>
                <p>Imagine a table here!</p>
            </div>
            <div>
                <h4>Inventory Alerts</h4>
                <p>And an evil, scary table here!</p>
            </div>

        </div>
    </Container>
</PageLayout>

application/blueprints/templates/homepage.html
{% extends "base.html" %}

{% block content %}
    <div class="max-w-5xl mx-auto px-4">
        <h1 class="underline decoration-8 decoration-violet-400">mochiOMS</h1>
        <p>Operations Management, made easy.</p>
        <form class="mb-10" action="{{url_for('login.login')}}" method="post">
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">

            {% with text='Login', color='violet' %}
                {% include "button.html" %}
            {% endwith %}
        </form>

        <form action="{{url_for('login.register')}}" method="post">
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
            <label for="first_name">First Name</label>
            <input type="first_name" name="first_name" id="first_name">
            <label for="last_name">Last Name</label>
            <input type="last_name" name="last_name" id="last_name">
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
            <label for="phone_number">Phone Number</label>
            <input type="phone_number" name="phone_number" id="phone_number">

            {% with text='Register', color='indigo' %}
                {% include "button.html" %}
            {% endwith %}
        </form>
    </div>
{% endblock content %}