application/blueprints/services/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required
from application.extensions import db, catalog, jp
from application.blueprints.services.models import *
from termcolor import cprint
from application.blueprints.services.data_validation import update_instance_fields


# An easy-to-find list of all available configurable options.
# Notably, Service is not present. The user gets a separate button for that.
all_types = [
    TextOption.url_type,
    TextareaOption.url_type,
    NumberOption.url_type,
    FloatOption.url_type,
    BooleanOption.url_type,
    DateOption.url_type,
    SelectOption.url_type,
]

# The URL class map is key for functionality in URLs.
# Since mochiOMS v2 has multiple tables for different option types,
# we can't guarantee the ID is unique.
# So, we create a url map. The URL will contain an attribute called
# 'url_type'.
# This dictionary performs on a lookup on this map and perform a query using the second URL piece,
# 'id'.
# So,
# Service.url_type is 'service'. We have a url coming in that's /service/1, which is mapped to the view() function.
# The dictionary looks up the word 'service' and finds it's related to the Service class. It performs a query on Service
# with the ID 1 and passes that to the Jinja template. Clever!

url_class_map = {
    Service.url_type: Service,
    TextOption.url_type: TextOption,
    TextareaOption.url_type: TextareaOption,
    NumberOption.url_type: NumberOption,
    FloatOption.url_type: FloatOption,
    BooleanOption.url_type: BooleanOption,
    DateOption.url_type: DateOption,
    SelectOption.url_type: SelectOption,
    Selectable.url_type: Selectable,
}


services_bp = Blueprint(
    "services", __name__, template_folder="templates", url_prefix="/services"
)


@services_bp.route("/", methods=["get"])
@services_bp.route("/<url_type>/<id>", methods=["get"])
def homepage(url_type=None, id=None):
    if url_type and id:
        model = url_class_map.get(url_type).query.get(id)
    else:
        model = None
    services = Service.query.filter_by(parent_service_id=None).all()

    return jp.render("services_homepage.html", model=model, services=services)


@services_bp.route("/new", methods=["POST"])
def new():
    data = request.form.to_dict()
    model = url_class_map.get(data.get("type_select"))()
    if hasattr(model, "parent_service_id"):
        model.parent_service_id = data.get("parent_service_id")
    elif hasattr(model, "select_option_id"):
        model.select_option_id = data.get("select_option_id")
    db.session.add(model)
    db.session.commit()

    return redirect(request.referrer)


@services_bp.route("/<url_type>/<id>/panel", methods=["GET"])
def panel(url_type, id):
    model = url_class_map.get(url_type).query.get(id)
    if model:
        return jp.render("services_view.html", service=model)
    else:
        flash(
            "Nothing of type '" + url_type + "' exists with ID " + str(id) + ".",
            "danger",
        )
        return redirect(url_for("services.homepage"))


@services_bp.route("/<url_type>/<id>/edit", methods=["GET"])
def edit(url_type, id):
    model = url_class_map.get(url_type).query.get(id)
    if model:
        return jp.render("services_edit.html", model=model, all_types=all_types)
    else:
        flash("Nothing of type " + model + " exists with ID " + str(id), "danger")
        return redirect(url_for("services.homepage"))


@services_bp.route("/<url_type>/<id>/edit/save", methods=["POST"])
def save(url_type, id):
    data = request.form.to_dict()
    model = url_class_map.get(url_type).query.get(id)
    if model:
        result = update_instance_fields(model, data)
        if result == True:
            flash("Changes saved.", "success")
            return redirect(
                url_for("services.edit", id=model.id, url_type=model.url_type)
            )
        elif result == False:
            flash("Something went wrong.", "danger")
            return redirect(
                url_for("services.edit", id=model.id, url_type=model.url_type)
            )
        elif result == None:
            flash("Content deleted.", "success")
            return redirect(url_for("services.homepage"))

    if not model:
        flash("No service under that ID.", "danger")
        return redirect(url_for("services.homepage"))

    return redirect(url_for("services.edit", id=model.id, url_type=model.url_type))


@services_bp.route("/search")
def search():
    # Get the "search" parameter from the query string
    search_term = request.args.get("search", "")

    # Get the "limit" parameter or default to 100 if it doesn't exist
    limit = int(request.args.get("limit", 100))

    # Query the Services model, filtering by name
    query = Service.query.filter(Service.name.ilike(f"%{search_term}%")).limit(limit)

    # Execute the query to get the results
    results = query.all()

    # Render the results in the 'services_table.html' template
    return jp.render("services_table.html", results=results)

application/blueprints/services/templates/services_edit.html
<PageLayout title="">
    <Container>

        <Navbar active-link = 'services'></Navbar>

        <h1>Editing "{{model.name}}"</h1>
        <a class="block max-w-fit" href="{{ url_for('services.homepage', id = model.id, url_type=model.url_type) }}">Go back</a>
        <form class="mt-4" action="{{url_for('services.save', id=model.id, url_type=model.url_type)}}" method="post">
            {{ model.to_form()|safe }}
            {% with input_type='checkbox', attr = 'delete', label = 'Delete (cannot be undone)', label_classes='text-red-500', input_classes="accent-red-500" %}
                {% include "form_controls.html" %}
            {% endwith %}
            {% with text="Save", color="violet" %}
                {% include "button.html" %}
            {% endwith %}
        </form>
        {% if model.url_type == 'service' %}
            <h2>Required fields</h2>
            {% if model.all_field_children != [] %}
                {% for child in model.all_field_children %}
                    <p>{{child.name}} (<a href="{{url_for('services.edit', id = child.id, url_type=child.url_type)}}">Edit</a>)</p>
                {% endfor %}
            {% else %}
                <p>No required fields.</p>
            {% endif %}
            <form action="{{url_for('services.new')}}" method="post">
                <input type="hidden" name="parent_service_id" value="{{model.id}}">
                <select name="type_select" id="type_select">
                    {% for type in all_types %}
                        <option value="{{type}}">{{type}}</option>
                    {% endfor %}
                </select>
                {% with text="Add New Field", color="violet" %}
                    {% include "button.html" %}
                {% endwith %}
            </form>
            <h2>Child services</h2>
            {% if model.child_services %}
                {% for child in model.child_services %}
                    <p>{{child.name}} (<a href="{{url_for('services.edit', id = child.id, url_type=child.url_type)}}">Edit</a>)</p>
                {% endfor %}
            {% else %}
                <p>No child services.</p>
            {% endif %}
            <form class="mt-4" action="{{url_for('services.new')}}" method="post">
                <input type="hidden" name="type_select" value="service">
                <input type="hidden" name="parent_service_id" value="{{model.id}}">
                {% with text="Add New Service", color="violet" %}
                    {% include "button.html" %}
                {% endwith %}
            </form>
        {% endif %}

        {% if model.url_type == 'select' %}
            <h2>Selectables</h2>
            {% for child in model.selectables %}
                <p>{{child.name}} (<a href="{{url_for('services.edit', id = child.id, url_type=child.url_type)}}">Edit</a>)</p>
            {% endfor %}
            <form class="mt-4" action="{{url_for('services.new')}}" method="post">
                <input type="hidden" name="type_select" value="selectable">
                <input type="hidden" name="select_option_id" value="{{model.id}}">
                {% with text="Add New Selectable", color="violet" %}
                    {% include "button.html" %}
                {% endwith %}
            </form>
        {% endif %}
        
        <h2>Parent</h2>
        {% if model.parent_service %}
            <p>{{model.parent_service.name}} (<a href="{{url_for('services.edit', id = model.parent_service_id, url_type = model.parent_service.url_type)}}">Edit</a>)</p>
        {% elif model.select_option %}
            <p>{{model.select_option.name}} (<a href="{{url_for('services.edit', id = model.select_option_id, url_type = model.select_option.url_type)}}">Edit</a>)</p>
        {% else %}
            <p>No parent service.</p>
        {% endif %}
    </Container>
</PageLayout>

application/blueprints/services/templates/services_homepage.html
<PageLayout title="Services">
    
    {% macro render_service(service) %}
    <a
        class="my-0 block mb-4 max-w-fit service-link"
        hx-get="{{url_for('services.panel', id = service.id, url_type=service.url_type) }}"
        hx-target="#panel-container"
        hx-swap="innerHTML"
        hx-push-url="/services/{{service.url_type}}/{{service.id}}"
        >{{service.name}}</a
    >
    {% if service.all_field_children %}
    <p class="faded-text m-0 ml-4">Required fields</p>
    <div class="ml-8">
        {% for child in service.all_field_children %} {{ render_service(child) }} {%
        endfor %}
    </div>
    {% endif %} {% if service.child_services %}
    <p class="faded-text m-0 ml-4">Child services</p>
    <div class="ml-8">
        {% for child in service.child_services %} {{ render_service(child) }} {%
        endfor %}
    </div>
    {% endif %} {% endmacro %}
    <div class="max-w-5xl mx-auto px-4 mt-6">
        {% with active_link='services' %} {% include "Navbar.jinja" %} {% endwith %}
    
        <h1>Services</h1>
        <div class="grid grid-cols-2">
            <div>
                {% if services %} {% for service in services %} {{
                render_service(service) }} {% endfor %} {% else %} Looks like you
                haven't added any <span class="font-semibold">Services</span> yet.
                Click the button below to get started. {% endif %}
                <form
                    class="mt-4"
                    action="{{url_for('services.new')}}"
                    method="post">
                    <input
                        type="hidden"
                        name="type_select"
                        value="service" />
                    {% with text="Add New Service", color="violet" %} {% include
                    "button.html" %} {% endwith %}
                </form>
                <DBSearch id="results" limit="True" url="{{ url_for('services.search')}}">Search your services...</DBSearch>
            </div>
            <div id="panel-container">
                {% if model %}
                    <div
                        hx-get="{{url_for('services.panel', id = model.id, url_type=model.url_type) }}"
                        hx-target="#panel-container"
                        hx-swap="innerHTML"
                        hx-push-url="/services/{{model.url_type}}/{{model.id}}"
                        hx-trigger="load"></div>
                {% else %}
                    <p class="faded-text">Nothing selected.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        document.querySelectorAll('.service-link').forEach(link => {
            link.addEventListener('click', function() {
                // Remove 'active-link' from all links
                document.querySelectorAll('.service-link').forEach(el => el.classList.remove('active-link'));
    
                // Add 'active-link' to the clicked link
                this.classList.add('active-link');
            });
        });
    </script>
    
</PageLayout>

application/blueprints/services/templates/services_table.html
<table>
    {% for result in results %}
        {{result.name}}
    {% endfor %}
</table>

application/blueprints/services/templates/services_view.html
<div>
    <h2 class="mt-1">{{service.name}}</h2>
    {% if service.is_archived %}
        <p class="text-amber-500"><span class="font-semibold">{{service.name}}</span> is archived. Edits can still be made, however, it is not useable in new orders.</p>
    {% endif %}
    <a href="{{ url_for('services.edit', id = service.id, url_type = service.url_type)}}">Edit this service</a>
    <p class="mb-0 faded-text">Type</p>
    <p class="mt-0">{{service.url_type|snake_to_upper}}</p>
    {% for attr, val in service.form_attribute_list.items() %}
        <p class="mb-0 faded-text">{{attr|snake_to_upper}}</p>
        <p class="mt-0">{{service|attr(attr)}}</p>
    {% endfor %}
</div>